### ISSUE TITLE
xfce: Auto-Suspend requests password

### ISSUE THREAD

**Issue by HopelessHarry** [linuxmint/mint20.2-beta#16]
Using xfce 20.2 beta. 
When system sleep mode is set in power manager, instead of auto-suspending after say 1 hour of inactivity, it hangs waiting for the user to input password. This is no good as usually the user is away from the computer, hence the reason for setting auto-suspend.

**Comment by Jildridge** [comment]
I can confirm some similar effect when using xfce live-session. However, I don't get a password request to enter suspend mode; instead I get a message telling me that none of the screen lock tools can run successfully and giving me the option to enter suspend mode manually. Switching manually to suspend works fine.
![Screenshot_2021-06-23_10-32-07](https://user-images.githubusercontent.com/42801814/123084446-69dc8100-d421-11eb-99a9-d5202a36e26b.png)

**Comment by HopelessHarry** [comment]
Hi Jildridge. Mine was an installed session. Yes that was the message. The password may well have been because the Screen Locked before Suspend kicked in, I can't remember now. Either way, suspend should happen automatically, in case the operator is away from the screen.

**Comment by Jildridge** [comment]
Hi HopelessHarry,
Perhaps I did not get any password prompt since there is no password available in live-mode. When I log-out and log-in again, I don't need any password. Therefore I think its the same 'bug' - and in all previous distros I used, suspend of course happend automatically after the set time limit.

**Comment by HopelessHarry** [comment]
This is the actual message I get when the system should auto-suspend after the specified time of inactivity
![Screenshot_2021-06-27_21-59-20](https://user-images.githubusercontent.com/52999728/123559347-66cff080-d793-11eb-9772-adddfc830fef.png)
.

**Comment by HopelessHarry** [comment]
A fix for this can be found here:
https://forums.linuxmint.com/viewtopic.php?f=57&t=259912&p=2025367#p2025367
Post 5 worked for me.

**Comment by mtwebster** [comment]
Can you run this:
```
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/inactivity-sleep-mode-on-battery -s 1
```

I think this is a setting issue - the default is to hibernate when idle, but that's not supported out of the box. If you open the settings page, it shows Suspend, but it's lying :)  The gui knows you can't hibernate, but it's not going back and overriding the setting (nor is the power manager).

This command will set it to suspend, and it should succeed. If you've used some workarounds please disable them and reboot first before trying this.

Thanks

**Comment by HopelessHarry** [comment]
Hi,
The command returns - Property "/xfce4-power-manager/inactivity-sleep-mode-on-battery" does not exist on channel "xfce4-power-manager".
Probably because I'm running 20.2 on a Desktop not a Laptop.
The fix in my last post resolves the Desktop issue perfectly. Changing lines 260 & 261 to yes.

**Comment by mtwebster** [comment]
Sorry I updated the command above, please try again when you get a chance.

**Comment by HopelessHarry** [comment]
Hi.
No that hasn't worked.
I still have the "Authentication is required to suspend the system" message.

**Comment by Jildridge** [comment]
@mtwebster I tried your command referring to posting no.2. It did not work. However, since I used the live-session, I could not reboot without losing the setting. Anyway,  simply logging-out and -in again didn't help.

**Comment by mtwebster** [comment]
I'm not sure a live session is reliable to test this on.

This is strange, I've tested this on multiple virtual machines and it's resolved the issue for me. I'm setting up real hardware to test now.

**Comment by HopelessHarry** [comment]
Could it be a power manager setting? Just so we're on the same page, I have my screen set to, blank after 5 mins, put to sleep after 10, & switch off after 15. On the Security tab - to Automatically lock the session when the Screensaver is activated. And delay in locking of 1 min.  Ans System - suspend after 1 hour. 
Hope this helps.

**Comment by Jildridge** [comment]
I disabled **light-locker**. Now automatic suspend works.

**Comment by mtwebster** [comment]
Ok sorry - I was testing idle-suspend only, without the locker involvement. It is indeed not working. My suggested fix up there does address not being able to suspend *without* the locker active, but it's not the main issue with the described scenario.

It's an bug that's been around for some time. I will see if there's a less invasive way to override the suspend and hibernate actions in policykit as I doubt we'll override the system one.

**Comment by clefebvre** [comment]
Does this workaround work? https://stijn.tintel.eu/blog/2015/09/11/polkit-requesting-root-password-to-suspend-after-updating-version-0112-to-0113

It doesn't look like there's much movement upstream on this despite the issue being known. I know Xfce recently implemented their own screensaver (this was the reason we used light-locker before, they just didn't have any). We might explore the possibility of shipping with xfce4-sceensaver in 20.3.

I'd be interested in feedback on xfce4-screensaver if you want to replace light-locker with it and tell us what you think.

I'll mark this as closed for now since it's not new despite being an important issue. We'll release as is and we'll keep track of this through the roadmap.
