### ISSUE TITLE
Search website directly from search menu

### ISSUE THREAD

**Issue by Kakapoudel7** [linuxmint/mint20.2-beta#68]
When I type 'linuxmint.com' on the search bar, it don't do anything ! please add a feature so that it detect website and redirect to the website through default browser.

**Comment by hyunsun1004** [comment]
Not the place for feature requests - bug reports on 20.2 Beta only.  LM doesn't open websites from the search bar.  If that's a feature you need, then use Windows 10.

**Comment by xenopeek** [comment]
Bit unclear. I guess you can mean either of three things:

1. When you type "linuxmint.com" in the Firefox address bar and press Enter, it doesn't go to the main website? I can't reproduce that problem. If I do the same it goes to the main website.
2. When you type "linuxmint.com" in the Firefox address bar the search suggestions only show, among other search suggestions from the search engine, the Start Page for Linux Mint Uma "linuxmint.com/start/uma/". That's the default homepage in Firefox. If you'd want search for "linuxmint.com" to suggest "linuxmint.com" (but why?) the main website would need to be added to the Firefox bookmarks.
3. Or you want a search engine in Firefox to search only on the "linuxmint.com" websites? You can add the search term site:linuxmint.com to your search query to limit search results to the Linux Mint websites.

I think if 1 is what you meant, troubleshoot why your internet isn't working. For 2 or 3 you can make a suggestion for that. Considering the behavior is no different from Linux Mint 20.1 I think this is beyond the scope of the bug squash.
