### ISSUE TITLE
Android Apps

### ISSUE THREAD

**Issue by Kakapoudel7** [linuxmint/mint20.2-beta#69]
During the Windows 11 launch program, we have heard about android apps being run in PC as well. so please cooperate with Android or other app store for the collabs and make it real to happen listening to clubhouse directly from my PC.

**Comment by hyunsun1004** [comment]
Not the place for feature requests - bug reports on 20.2 Beta only.  Please head over to Reddit or some other forum to discuss Windows 11 features.

**Comment by xenopeek** [comment]
This is beyond the scope of the bug squash for the Linux Mint 20.2 beta.

There are several (in the works) options to run Android apps on Linux. The one that is probably closest to what you want is https://anbox.io/. There are several other options. Another promising one is https://www.android-x86.org/ but you need to run that in a virtual machine. I don't know if you can use the Android app store with either. You'll likely need to download APKs. I'd say go experiment and maybe share what works best and the pros and cons of each on the forums and maybe come up with a suggestion from that.
